### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by FighterShan** [xingstarx/InkeVerticalViewPagerLive#3]
使用了相同的VerticalViewPager,加载的逻辑一样。不同的是我使用了网易的播放器
出现了问题1：滑动的时候，不是出现下一页的背景图片，而是黑屏
对上面问题的处理：
videoView.setZOrderOnTop(true); //surfaceview放置在window最上面
 videoView.getHolder().setFormat(PixelFormat.TRANSPARENT);//设置surfaceview的像素格式
但是这样处理出现问题2，出现在第一句代码。他把surfaceview放置在window最上面，导致roomcontainner的内容显示不了（但，第一句又不能去掉，否则又是黑屏）
所以，我想问的问题是：作者有没有遇到过问题1，或者问题2，或者能提供点线索或思路。
感谢

**Comment by xingstarx** [comment]
1. videoView本质还是是surfaceview，滑动的话是会存在问题的。建议用TextureView
2. 你把videoView设置到window最上层，就会导致聊天室显示不出来，类似的，像礼物动画也出不来

所以建议用TextureView

**Comment by xingstarx** [comment]
我看了下网易云的android文档上说了， 是有VideoView 继承自 TextureView的
https://vcloud.163.com/docs/player/androidGuide.html

**Comment by FighterShan** [comment]
嗯  谢谢哈
后面看下替换成TextureView，看下效果

**Comment by FighterShan** [comment]
看过了  没问题~~
