### ISSUE TITLE
删除已有布局的判断错误

### ISSUE THREAD

**Issue by liuandy1** [xingstarx/InkeVerticalViewPagerLive#5]
position < 0 && viewGroup.getId() != mCurrentItem 这个应该是
position != 0 && viewGroup.getId() != mCurrentItem吧，因为只小于0 当往上切的时候并不能把之前的删除哈

**Comment by xingstarx** [comment]
你改成这个position != 0 && viewGroup.getId() != mCurrentItem是可以的，我写的position < 0 && viewGroup.getId() != mCurrentItem  这个只是用来处理往下切的情况。但是当往上切时，只有在需要加载直播视频的时候，这个时候会先判断，视频所在的mRoomContainer是否从ViewPager的itemView中移除出去了，如果没有先移除，然后在进行添加。。

```java
// 满足此种条件，表明需要加载直播视频，以及聊天室了
                if (viewGroup.getId() == mCurrentItem && position == 0 && mCurrentItem != mRoomId) {
                    if (mRoomContainer.getParent() != null && mRoomContainer.getParent() instanceof ViewGroup) {
                        ((ViewGroup) (mRoomContainer.getParent())).removeView(mRoomContainer);
                    }
                    loadVideoAndChatRoom(viewGroup, mCurrentItem);
                }
```

由于存在这个判断，所以就不会出现问题的。

还是是我写的不够精简，最开始以为这样写，会效果好一点。。其实并没有测试验证过。

按道理只需要在每次添加前先移除就可以了。。这个需要测试下才好。。

**Comment by liuandy1** [comment]
谢谢解答~  position != 0 && viewGroup.getId() != mCurrentItem 测试了也有问题，把这些判断移到ViewPager中onPageSelected方法是否会跟清晰呢？  还有上面有同学Issues 说把播放器放在RoomFragment中加载，我之前就是这样做的，但发现会影响播放器的加载时间，影响直播的秒开优化，所以就现在就采用你的思路了。(*@ο@*) ~
