### ISSUE TITLE
如果本是主Activity有布局，视频会盖住activity之前的布局=-=

### ISSUE THREAD

**Issue by dujingxue1997** [xingstarx/InkeVerticalViewPagerLive#6]
为什么不把整体布局都在写在Room里面呢=-= 还要去加一个item这么布局。。。望解答。

**Comment by dujingxue1997** [comment]
标题写错了，是如果本身主Activity

**Comment by xingstarx** [comment]
viewPager 需要有item布局啊，这个item布局只是占位的，最终还是需要让textureView或者聊天室位于当前的itemView上
