### ISSUE TITLE
adapter 中item 布局的问题

### ISSUE THREAD

**Issue by sunzq19931016** [xingstarx/InkeVerticalViewPagerLive#7]
adapter 中 item 布局进行场景的显示，将主要的控件比如TextView 或者 ImageView 显示并且进行变换，当执行transformPage 方法后 将item 中布局的Fragment 替换 视频 是否可行？？？

**Comment by sunzq19931016** [comment]
十分感谢

**Comment by xingstarx** [comment]
我觉得可行额，只不过判断条件应该要处理好，transformPage执行的过程中，相邻的两个itemView都会执行，需要处理好判断边界，我就得可行。

抱歉这么晚才回复，希望对你有用

**Comment by sunzq19931016** [comment]
如何处理两个相邻的itemview 这个问题对我很苦恼，谢谢
