### ISSUE TITLE
请教一下，我测试使用了多个视频地址，但翻页时一直只播放第一个地址的视频，请问需要如何改一下代码？

### ISSUE THREAD

**Issue by 1214658495** [xingstarx/InkeVerticalViewPagerLive#8]

**Comment by xingstarx** [comment]
是使用的我的demo么？如果是我写的这个demo的话，你的多个视频地址是添加在mVideoUrls这个List里面么，你需要修改我的这个代码
```java
private void generateUrls() {
        for (int i = 0; i < 10; i++) {
            mVideoUrls.add(DEFAULT_TEST_URL);
        }
    }
```
mVideoUrls中添加成你自己的播放地址就可以了

**Comment by 1214658495** [comment]
感谢你的回复，是的我把上面的地址都改了，然后每一次mVideoView.setVideoPath(mVideoUrls.get(position))这里的地址都更新了，但播放的视频一直是第一个，如果翻页的话就会接着第一个播放。请问你有测过多个地址播放的效果吗？谢谢🙏
